### ISSUE TITLE
ECC-EasyCalcCheck-Plus errors

### ISSUE THREAD

**Issue by zyzaktomek** [Kubik-Rubik/ECC-EasyCalcCheck-Plus#1]
Hi

Joomla 3.7.4
PHP. 7.1.7

I set ECC just to Community Builder protection. On CB registration form I got
Notice: Undefined index: username in /home/zyzak/domains/norwegia1.pl/public_html/administrator/components/com_spamprotect/models/spamprotect.php on line 27

Notice: Undefined index: email1 in /home/zyzak/domains/norwegia1.pl/public_html/administrator/components/com_spamprotect/models/spamprotect.php on line 28

Notice: Undefined index: email1 in /home/zyzak/domains/norwegia1.pl/public_html/administrator/components/com_spamprotect/models/spamprotect.php on line 122

Notice: Undefined property: PlgUserSpamProtect::$action in /home/zyzak/domains/norwegia1.pl/public_html/plugins/user/spamprotect/spamprotect.php on line 153

Notice: Undefined property: PlgUserSpamProtect::$action in /home/zyzak/domains/norwegia1.pl/public_html/plugins/user/spamprotect/spamprotect.php on line 184

Notice: Undefined property: PlgUserSpamProtect::$action in /home/zyzak/domains/norwegia1.pl/public_html/plugins/user/spamprotect/spamprotect.php on line 199

Notice: Undefined index: username in /home/zyzak/domains/norwegia1.pl/public_html/administrator/components/com_spamprotect/models/spamprotect.php on line 27

Notice: Undefined index: email1 in /home/zyzak/domains/norwegia1.pl/public_html/administrator/components/com_spamprotect/models/spamprotect.php on line 28

Notice: Undefined index: email1 in /home/zyzak/domains/norwegia1.pl/public_html/administrator/components/com_spamprotect/models/spamprotect.php on line 122

Notice: Undefined property: PlgUserSpamProtect::$action in /home/zyzak/domains/norwegia1.pl/public_html/plugins/user/spamprotect/spamprotect.php on line 153

Notice: Undefined property: PlgUserSpamProtect::$action in /home/zyzak/domains/norwegia1.pl/public_html/plugins/user/spamprotect/spamprotect.php on line 184

Notice: Undefined property: PlgUserSpamProtect::$action in /home/zyzak/domains/norwegia1.pl/public_html/plugins/user/spamprotect/spamprotect.php on line 199

**Comment by Kubik-Rubik** [comment]
Hi @zyzaktomek!

This messages have nothing to do with ECC...

"com_spamprotect" and "plugins/user/spamprotect" are not related to EasyCalcCheck Plus!

Cheers
